name: viking_scouter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.0
  permission_handler: '^4.2.0+hotfix.3'
  share_extend: ^1.1.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Aileron
      fonts:
        - asset: fonts/Aileron-BlackItalic.otf
          weight: 500
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSansRegular.ttf
          weight: 400
        - asset: fonts/OpenSans300.ttf
          weight: 300